[package]
name = "react-project-backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.9"
ic-cdk = "0.11"
ic-cdk-timers = "0.5"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"